name: Build release

on:
  push:
    branches:
      - 'releases/v*'
    tags-ignore:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'v16.13.2'
          registry-url: 'https://registry.npmmirror.com'

      - name: Install pnpm
        run: npm install -g pnpm@6.24.2

      - name: Build lib
        run: |
          pnpm install
          pnpm build

      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            lib
            node_modules
