name: Build Production Dependencies and Code
on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/v*'
    tags-ignore:
      - '*.*'

jobs:
  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'v16.13.2'
          registry-url: 'https://registry.npmmirror.com'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Clobber lib
        run: rm -rf lib

      - name: Set up .gitignore
        run: |
          sed -i -e's/^lib/# lib/' -e's/^node_module/# node_modules/' .gitignore

      - name: Build
        run: |
          yarn install
          yarn build

      # Workflow dispatch event that pushes the current version to the release branch.
      # From here the secondary `build-release` deployment workflow will trigger to build the dependencies.
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: releases/v1
          folder: .
      # - name: Commit and Push
      #   # Keep the run green if the commit fails for the lack of changes
      #   continue-on-error: True
      #   run: |
      #     git config user.email "filestorage-action"
      #     git config user.name "filestorage-action@users.noreply.github.com"
      #     git add .
      #     git commit -m "Deploy Production Code for Commit ${{ github.sha }} 🚀"
      #     git push
