name: Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout file date
      uses: moonrailgun/branch-filestorage-action@v1.2.0
      with:
        path: cookie
    - name: Read and show
      run: touch cookie && cat cookie
    - name: print path
      run: pwd
    - name: update cookie
      run: python main.py
